#!/bin/bash
set -e

cd /Users/echopeso/research_accelerator

# Install project in editable mode if pyproject.toml exists and ra is not importable
if [ -f "pyproject.toml" ]; then
    if ! python3 -c "import ra" 2>/dev/null; then
        echo "Installing project in editable mode..."
        python3 -m pip install -e ".[dev]" --quiet
    fi
fi

# Verify baseline fixtures exist
if [ ! -d "tests/fixtures/baseline_output" ]; then
    echo "ERROR: Baseline fixtures not found at tests/fixtures/baseline_output/"
    echo "Run the pipeline first: cd pipeline && python preprocess_data_v2.py"
    exit 1
fi

# Verify dataset exists
if [ ! -f "data/eurusd_1m_2024-01-07_to_2024-01-12.csv" ]; then
    echo "ERROR: Dataset not found at data/eurusd_1m_2024-01-07_to_2024-01-12.csv"
    exit 1
fi

# Count baseline fixtures
FIXTURE_COUNT=$(ls -1 tests/fixtures/baseline_output/*.json 2>/dev/null | wc -l | tr -d ' ')
echo "Baseline fixtures: ${FIXTURE_COUNT} JSON files."

# Verify River parquet data exists (Phase 2)
RIVER_ROOT="${RIVER_ROOT:-$HOME/phoenix-river}"
if [ -d "${RIVER_ROOT}/EURUSD" ]; then
    RIVER_YEARS=$(ls -d "${RIVER_ROOT}/EURUSD"/20* 2>/dev/null | wc -l | tr -d ' ')
    echo "River data: ${RIVER_YEARS} years of EURUSD parquet at ${RIVER_ROOT}"
else
    echo "WARNING: River parquet data not found at ${RIVER_ROOT}/EURUSD/"
    echo "River adapter tests requiring parquet will be skipped."
fi

# Phase 3: Generate comparison fixture data if not present
if [ ! -f "site/eval/evaluation_run.json" ]; then
    if [ -f "site/generate_eval_data.sh" ]; then
        echo "Generating Phase 3 comparison fixture data..."
        bash site/generate_eval_data.sh || echo "WARNING: Fixture generation failed. Run manually: bash site/generate_eval_data.sh"
    else
        echo "NOTE: site/generate_eval_data.sh not yet created. Fixture data will be generated by the foundation feature."
    fi
else
    echo "Phase 3 fixture data: present in site/eval/"
fi

# Phase 3.5: Check validation mode infrastructure
if [ -f "site/detect.py" ]; then
    echo "Phase 3.5 detect.py: present"
else
    echo "NOTE: site/detect.py not yet created (Phase 3.5 CLI generator)"
fi

if [ -f "site/serve.py" ]; then
    echo "Phase 3.5 serve.py: present"
else
    echo "NOTE: site/serve.py not yet created (Phase 3.5 write server)"
fi

if [ -d "site/data/detections" ]; then
    WEEK_COUNT=$(ls -1 site/data/detections/*.json 2>/dev/null | wc -l | tr -d ' ')
    echo "Phase 3.5 validation data: ${WEEK_COUNT} weeks generated"
else
    echo "NOTE: No validation data generated yet. Run: python3 site/detect.py --start 2025-09-01 --end 2026-02-28 --config configs/locked_baseline.yaml --output site/data/"
fi

echo "Environment ready."
